service: product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

plugins:
  - serverless-auto-swagger

functions:
  getProductsList:
    handler: getProductsList.getProductsList
    environment:
      PRODUCTS_TABLE: "Products"
      STOCKS_TABLE: "Stocks"
    package:
      include:
        - node_modules/**
    events:
      - http:
          path: /product
          method: get
          cors: true
  getProductsById:
    handler: getProductsById.getProductsById
    environment:
      PRODUCTS_TABLE: "Products"
    package:
      include:
        - node_modules/**
    events:
      - http:
          path: /product/{productId}
          method: get
          cors: true
  getStocksList:
    handler: getStocksList.getStocksList
    environment:
      STOCKS_TABLE: "Stocks"
    package:
      include:
        - node_modules/**
    events:
      - http:
          path: /stocks
          method: get
          cors: true
   createProduct:  
    handler: createProduct.createProduct
    environment:
      PRODUCTS_TABLE: "Products"
    package:
      include:
        - node_modules/**
    events:
      - http:
          path: /products
          method: post 
          cors: true