service: import-service
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::uploaddded"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::uploaddded/*"

functions:
  importProductsFile:
    handler: importProductsFile.importProductsFile
    events:
      - http:
          method: get
          path: /import
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: importFileParser.importFileParser
    events:
      - s3:
          bucket: uploaddded
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
