service: import-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListBucket
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource:
            - arn:aws:s3:::aws-upload-buckett
            - arn:aws:s3:::aws-upload-buckett/*

functions:
  importProductsFile:
    handler: importProductsFile.importProductsFile
    events:
      - http:
          method: get
          path: /import
          cors: true
          request:
            parameters:
              querystrings:
                name: true

  importFileParser:
    handler: importFileParser.importFileParser
    events:
      - s3:
          bucket: aws-upload-buckett
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded
          existing: true
